spring:
  application:
    name: board-service
  profiles:
    active: default
  cloud:
    config:
      enabled: true
  dataSource:
    jdbcUrl: jdbc:mysql://localhost:3306/easytracking2?autoReconnect=true&useSSL=false
    username: easytrackinguser2
    password: EasyTracking2!
    driver-class-name: com.mysql.jdbc.Driver
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    useLocalTransactionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8100
